S3 i13
Sur0vy/url_shortner pull request #16
Opened 2022-05-09 14:32 UTC by Sur0vy

2022-05-12 14:58 UTC, Bazys requested changes

2022-05-12 14:58 UTC, Bazys commented on internal/database/database.go
> +func Connect() {
эту часть рекомендую перенести в конструктор DBUserStorage

2022-05-12 14:58 UTC, Bazys commented on internal/database/database.go
> +func CreateTables() {
Это тоже можно оформить одним из методов там же.
Всё ради того что бы не пользоваться глобальной переменной

2022-05-12 14:58 UTC, Bazys commented on internal/storage/DBstorage.go
> +func (s *DBStorage) GetShortURL(fullURL string) (*ShortURL, error) {
context.Background() - может создаваться только в main.
Здесь необходимо использовать контекст хэндлера.

2022-05-12 19:37 UTC, Sur0vy commented on internal/storage/DBstorage.go
> +func (s *DBStorage) GetShortURL(fullURL string) (*ShortURL, error) {
понятно, поправлю

2022-05-13 20:55 UTC, Sur0vy commented on internal/database/database.go
> +func Connect() {
поправлено

2022-05-13 20:55 UTC, Sur0vy commented on internal/database/database.go
> +func CreateTables() {
поправил

2022-05-15 11:34 UTC, Bazys approved these changes

2022-05-22 05:10 UTC, merged